name: "Debug exports"
on: [push, pull_request]

jobs:
  export-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export Android
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'tools platform-tools platforms cmdline-tools cmake build-tools ndk'
    - name: Build
      id  : export
      uses: firebelley/godot-export@v7.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
        relative_project_path: ./
        export_debug: true
        archive_output: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android
        path: ${{ steps.export.outputs.archive_directory }}/*
