name: "Debug exports"
on: [push, pull_request]

jobs:
  export-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export Android
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'tools platform-tools platforms;android-35 cmdline-tools;latest cmake;3.22.1 build-tools;35.0.0 ndk;28.1.13356709'
    - name: Build
      id  : export
      uses: firebelley/godot-export@v7.0.0
      with:
        godot_executable_download_url: https://downloads.godotengine.org/?version=4.5.1&flavor=rc1&slug=linux.x86_64.zip&platform=linux.64
        godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.5.1&flavor=rc1&slug=export_templates.tpz&platform=templates
        relative_project_path: ./
        export_debug: true
        archive_output: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android
        path: ${{ steps.export.outputs.archive_directory }}/*
